name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
		      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
		      aws-region: us-east-1
	    - name: Deploy static website to s3 bucket
	      run: aws s3 . s3://aws-git-actions  --delete
